version: '{build}'
init:
  clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      VS_VERSION: 2019
      WIN_SDK: 10.0.18362.0
      BUILD_ARCH: x64

configuration:
  - Release

install:
 - git submodule update --init --recursive --depth 5
 - set QTDIR32=C:\Qt\5.15\msvc2019
 - set QTDIR64=C:\Qt\5.15\msvc2019_64
 - call "%programfiles(x86)%\Microsoft Visual Studio\%VS_VERSION%\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64 %WIN_SDK% && "%QTDIR64%\bin\qmake.exe" -tp vc -r

build_script:
 - msbuild /t:Build /p:Configuration=Release;PlatformToolset=v142