version: '{build}'
init:
  clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      qt: 5.12\msvc2017_64
      VS_VERSION: 2017
      BUILD_ARCH: x64

configuration:
  - Release

install:
- git submodule update --init --recursive --depth 5
- set PATH=C:\Qt\%qt%\bin;%PATH%;
- dir "C:\Program Files (x86)\Windows Kits\10\include\"
- IF "%VS_VERSION%" == "2017" (call "%programfiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64 10.0.17134.0 && "C:\Qt\%qt%\bin\qmake.exe" -tp vc -r)
- cd file-commander-core\core-tests\
- IF "%VS_VERSION%" == "2017" (call "%programfiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64 10.0.17134.0 && "C:\Qt\%qt%\bin\qmake.exe" -tp vc -r)
- cd ..\..\

build_script:
 - IF "%VS_VERSION%" == "2017" (msbuild file-commander.sln /t:Build /p:Configuration=Release;PlatformToolset=v141)
 - cd file-commander-core\core-tests\
 - IF "%VS_VERSION%" == "2017" (msbuild /t:Build /p:Configuration=Release;PlatformToolset=v141)
 - cd ..\..\